# SAFE PAPER TRADING CONFIGURATION
# This configuration ensures NO REAL MONEY is used

# Trading Configuration - PAPER TRADING ONLY
trading:
  cycle_interval: 300
  base_currency: "USDT"
  trading_pairs:
    - "BTC/USDT"
    - "ETH/USDT"
  paper_trading: true          # ✅ MUST BE TRUE for paper trading
  timeframe: '1h'
  close_positions_on_shutdown: true
  risk_management:
    max_drawdown: 0.2
    daily_loss_limit: 0.05

# Exchange Configuration - TESTNET ONLY, NO MAINNET FALLBACK
exchange:
  name: 'binance'
  testnet: true
  mainnet_fallback: false
  testnet_api:
    key: '4d9czgcBbpnaW6FBr1zDz70kmi9BVCt1Yguam6eg3H8l10sP3irR5uGol51IDEDC'
    secret: 'Y5IQkFxHZw5OHJLeXzZvFW5rTPEArlLYCVMldqn07CGGCXrGPyKAOrBci7u9GYg0'
  
  mainnet_api:
    key: 'your_key'
    secret: 'your_secret'

# Market Analysis Configuration
market_analysis:
  update_interval: 300
  indicators:
    rsi:
      period: 14
    macd:
      fast_period: 12
      slow_period: 26
      signal_period: 9
    bollinger:
      period: 20
      std_dev: 2

# Execution Configuration
execution:
  max_positions: 10
  position_size: 0.1
  risk_per_trade: 0.02
  stop_loss: 0.05
  take_profit: 0.15

# Strategy Configuration
strategies:
  bull:
    rsi_threshold: 60
    trend_threshold: 0.02
    min_volume: 1000000
    min_confidence: 0.65
    max_positions: 3
  bear:
    rsi_threshold: 40
    trend_threshold: -0.02
    min_volume: 1000000
    min_confidence: 0.70
    max_positions: 2
  ranging:
    range_threshold: 0.03
    volume_threshold: 800000
    min_confidence: 0.65
    max_positions: 3
  volatile:
    volatility_threshold: 0.04
    volume_multiplier: 1.5
    min_confidence: 0.75
    max_positions: 2

# Logging Configuration
logging:
  level: 'INFO'
  log_decisions: true
  log_trades: true